tinyMCE.addI18n('en.mt', {
    font_size_smaller: "Decrease Text Size",
    font_size_larger: "Increase Text Size",
    bold: "Bold",
    italic: "Italic",
    underline: "Underline",
    strikethrough: "Strikethrough",
    insert_link: "Link",
    insert_email: "Email Link",
    indent: "Begin Blockquote",
    outdent: "End Blockquote",
    insert_unordered_list: "Bulleted List",
    insert_ordered_list: "Numbered List",
    justify_left: "Left Align Text",
    justify_center: "Center Text",
    justify_right: "Right Align Text",
	insert_image: "Insert image",
	insert_file: "Insert file",
	source_mode: "HTML Mode"
});
