tinyMCE.addI18n(tinymce.settings.language, {
    "class_name": trans("Class Name"),
    "Bold": trans("Bold (Ctrl+B)"),
    "Italic": trans("Italic (Ctrl+I)"),
    "Underline": trans("Underline (Ctrl+U)"),
    "Strikethrough": trans("Strikethrough"),
    "Blockquote": trans("Block Quotation"),
    "Bullet list": trans("Unordered List"),
    "Numbered list": trans("Ordered List"),
    "Horizontal line": trans("Horizontal Line"),
    "Link": trans("Insert/Edit Link"),
    "Remove link": trans("Unlink"),
    "Undo": trans("Undo (Ctrl+Z)"),
    "Redo": trans("Redo (Ctrl+Y)"),
    "Text color": trans("Select Text Color"),
    "Background color": trans("Select Background Color"),
    "Clear formatting": trans("Remove Formatting"),
    "Justify": trans("Align Left"),
    "Align center": trans("Align Center"),
    "Align right": trans("Align Right"),
    "Increase indent": trans("Indent"),
    "Decrease indent": trans("Outdent"),

    mt_insert_link: trans('Insert Link'),
    mt_insert_html: trans('Insert HTML'),
    mt_insert_image: trans('Insert Image Asset'),
    mt_insert_file: trans('Insert Asset Link'),
    mt_fullscreen: trans('Toggle Fullscreen Mode'),
    mt_source_mode: trans('Toggle HTML Edit Mode'),

    // HTML mode
    mt_source_bold: trans('Strong Emphasis'),
    mt_source_italic: trans('Emphasis'),
    mt_source_blockquote: trans('Block Quotation'),
    mt_source_unordered_list: trans('Unordered List'),
    mt_source_ordered_list: trans('Ordered List'),
    mt_source_list_item: trans('List Item')
});
