#!/usr/bin/perl -w
use strict;

use lib '../../lib';
use lib '../../extlib';

use Test::Harness;
use DirHandle;
use File::Spec;

use MT;

# perl diags output. verbose switch???

my @files;
my $t = $ARGV[0] || 't';
my $path = File::Spec->catdir($ENV{PWD},$t);
if (my $dir = DirHandle->new($path)) {
    while (defined(my $x = $dir->read)) {
        my $file = File::Spec->catfile(File::Spec->curdir,$t,$x);
        push @files, $file if -f $file;
    }
}
runtests(sort @files);

__END__

map { print "$_\n" } keys %MT::Plugins;
print "defined is ".defined($MT::Plugins{'nofollow/nofollow.pl'});
print "\n";
print "enabled is ".$MT::Plugins{'nofollow/nofollow.pl'}{enabled};
print "\n";

