tinyMCE.addI18n(tinymce.settings.language + '.advanced', {
    "bold_desc": trans("Bold (Ctrl+B)"),
    "italic_desc": trans("Italic (Ctrl+I)"),
    "underline_desc": trans("Underline (Ctrl+U)"),
    "striketrough_desc": trans("Strikethrough"),
    "blockquote_desc": trans("Block Quotation"),
    "bullist_desc": trans("Unordered List"),
    "numlist_desc": trans("Ordered List"),
    "hr_desc": trans("Horizontal Line"),
    "link_desc": trans("Insert/Edit Link"),
    "unlink_desc": trans("Unlink"),
    "undo_desc": trans("Undo (Ctrl+Z)"),
    "redo_desc": trans("Redo (Ctrl+Y)"),
    "forecolor_desc": trans("Select Text Color"),
    "backcolor_desc": trans("Select Background Color"),
    "removeformat_desc": trans("Remove Formatting"),
    "justifyleft_desc": trans("Align Left"),
    "justifycenter_desc": trans("Align Center"),
    "justifyright_desc": trans("Align Right"),
    "indent_desc": trans("Indent"),
    "outdent_desc": trans("Outdent")
});
