## -*- mode: perl; coding: utf-8 -*-

# These modules are installed in extlib directory.
#requires 'CGI';
#requires 'Image::Size';
#requires 'CGI::Cookie';
#requires 'LWP::UserAgent';

# This is a core module, but there may be the environment
# that this module is not installed...
requires 'File::Spec', '0.8';

requires 'DBI', '1.21';
requires 'DBD::mysql';
feature 'mssqlserver', 'MSSQLServer support' => sub {
    requires 'DBD::ODBC', '1.25';
};
feature 'oracle', 'Oracle Database support' => sub {
    requires 'DBD::Oracle', '1.25';
};

recommends 'Digest::SHA';
recommends 'Plack';
recommends 'CGI::PSGI';
recommends 'CGI::Parse::PSGI';
recommends 'XMLRPC::Transport::HTTP::Plack';
recommends 'HTML::Entities';
recommends 'HTML::Parser';
recommends 'SOAP::Lite', '0.5';
recommends 'File::Temp';
recommends 'Scalar::Util';
recommends 'List::Util';
recommends 'Image::Magick';
recommends 'GD';
recommends 'Imager';
recommends 'IPC::Run';
recommends 'Storable';
recommends 'Crypt::DSA';
recommends 'Crypt::SSLeay';
recommends 'Cache::File';
recommends 'MIME::Base64';
recommends 'XML::Atom';
recommends 'Cache::Memcached';
recommends 'Archive::Tar';
recommends 'IO::Compress::Gzip';
recommends 'IO::Uncompress::Gunzip';
recommends 'Archive::Zip';
recommends 'XML::SAX';
recommends 'Digest::SHA1';
recommends 'Net::SMTP';
recommends 'Authen::SASL';
recommends 'Net::SMTP::SSL';
recommends 'Net::SMTP::TLS';
recommends 'IO::Socket::SSL';
recommends 'Net::SSLeay';
recommends 'Safe';
recommends 'Digest::MD5';
recommends 'Text::Balanced';
recommends 'XML::Parser';
recommends 'Time::HiRes';
recommends 'Mozilla::CA';
recommends 'XML::SAX::ExpatXS';
recommends 'XML::SAX::Expat';
recommends 'XML::LibXML::SAX';

on 'test' => sub {
    requires 'Clone';
    requires 'DateTime';
    requires 'DateTime::TimeZone';
    requires 'PHP::Serialization';
    requires 'pQuery';
    requires 'DBD::SQLite';
    requires 'Test::Base';
    requires 'Test::Class';
    requires 'Test::Data';
    requires 'Test::Deep';
    requires 'Test::File';
    requires 'Test::LeakTrace';
    requires 'Test::MockModule';
    requires 'Test::MockObject';
    requires 'Test::Pod::Coverage';
};
