#!/usr/bin/perl -w
use strict;

use lib 'lib', '../lib';
use MT::Bootstrap;
use MT;
use MT::PluginData;

use Data::Dumper;
$Data::Dumper::Terse = 1;
$Data::Dumper::Indent = 1;
$Data::Dumper::Quotekeys = 0;
$Data::Dumper::Sortkeys = 1;

my $mt = new MT;
my $plugin = $ARGV[0];
my $scope = $ARGV[1] || 'system';
if (!$plugin) {
    print "usage: $0 <plugin_name> [<scope>]\n";
    exit 1;
}

my $config = MT::PluginData->load({
    plugin => $plugin,
    key => $scope eq 'system' ? 'configuration' : 'configuration:' . $scope
});
if (!$config) {
    print "(None)\n";
} else {
    my $data = $config->data;
    my $dump = Dumper($data);
    print $dump;
}
